apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
        - name: back-ventas
          image: 075692576990.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: back-ventas-secret
                  key: SPRING_PROFILES_ACTIVE
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: back-ventas-service
spec:
  selector:
    app: back-ventas
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP